### ISSUE TITLE
How do I create single secret key token with multiple IP support?

### ISSUE THREAD

**Issue by keermanish** [plesk/api-php-lib#105]
Hello Team,

I have a requirement where I need to create a secret key to support multiple IP addresses.

Currently, I'm using `secretKey()->create($ip)` method _(defined under `PleskX\Api\InternalClient` class)_ to create a secret key. I checked the `swagger.yml`, we do have `/api/v2/auth/keys` API wherein we can pass the `ips`.

So my query is, **Do we have any such way to pass multiple IP addresses in `secretKey()->create()` method**?

Note: for single IP `create` method is working fine, but I'm not sure how can I pass multiple IP addresses.

Thanks

**Comment by sibprogrammer** [comment]
It is possible to do it using comma separated list of values. See c8a200eaddc8c7f89ad594cdca1e4a9e5fc5e2f2
