### ISSUE TITLE
Missing mail feature

### ISSUE THREAD

**Issue by ghermans** [plesk/api-php-lib#11]
At this point managing mail has not been implemented.(https://docs.plesk.com/en-US/12.5/api-rpc/reference/managing-mail.34477/)

 @sibprogrammer are you planning to add this ?

**Comment by sibprogrammer** [comment]
I hope yes :)

**Comment by beatbesmer** [comment]
We would be happy too.

**Comment by sibprogrammer** [comment]
Two last merges were referenced by mistake.

**Comment by sibprogrammer** [comment]
The basic CRUD operations are available. Future improvements are the subject of separate requests.
