### ISSUE TITLE
Attempt to read property "pname" on null

### ISSUE THREAD

**Issue by pindab0ter** [plesk/api-php-lib#116]
When requesting all resellers from a server that doesn't have resellers enabled (Plesk Web Pro edition) I'm getting this error:

```php
$client->reseller()->getAll(); // Attempt to read property "pname" on null
```

I expect this to just return an empty array since there are no resellers.

PHP: 8.1.6
Laravel: 9.19.0
plesk/api-php-lib: 1.1.3

**Comment by sibprogrammer** [comment]
Thank you for your report! The issue has been fixed in the master branch.
