### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by evrifaessa** [plesk/api-php-lib#118]
Hey, we are planning to use this library in our project [FOSSBilling](https://fossbilling.org), but seems like some of the new features don't appear yet in the new releases.

We specifically need the `setProperties` feature. It exists in the master branch but our project has its `minimum-stability` set to true in the Composer.json file.

Can you give us an ETA for a new release?

**Comment by evrifaessa** [comment]
@abashurov hey, anything new about this? We're waiting for your release to publish our integration.

**Comment by sibprogrammer** [comment]
Thank you for notifying us. The new release v2.0.0 is available. It's stable and ready for production use.
