### ISSUE TITLE
TypeError when calling get() with no results

### ISSUE THREAD

**Issue by SteenSchutt** [plesk/api-php-lib#119]
The `Site::get()` method is type hinted to always return a GeneralInfo struct, but it just mindlessly returns the result from `reset($items)`, which returns false when the array is empty.

Furthermore, it seems quite unhelpful to get multiple results back from the API and then just returning the first one. Considering this is already published as a public interface, I would suggest making the return type nullable and then changing `return reset($items);` to `return reset($items) ?: null`. Then add some kind of method that would return all results and call it `find`, `search` or something like that.

That way it should be possible to remedy the issue without breaking compatibility (Beyond people working around the issue by catching the TypeError that arises when there are no results).

```
PHP Fatal error:  Uncaught TypeError: PleskX\Api\Operator\Site::get(): Return value must be of type PleskX\Api\Struct\Site\GeneralInfo, bool returned in ~/Git/project/vendor/plesk/api-php-lib/src/Api/Operator/Site.php:61
Stack trace:
#0 ~/Git/project/init.php(11): PleskX\Api\Operator\Site->get()
#1 {main}
  thrown in ~/Git/project/vendor/plesk/api-php-lib/src/Api/Operator/Site.php on line 61
```

**Comment by sibprogrammer** [comment]
It should return `PleskX\Api\Exception: Site does not exist` in most cases.
Could you share which field-value pair you use in the `site->get()` call?

> Then add some kind of method that would return all results

It's present already (`getAll` method).

**Comment by SteenSchutt** [comment]
It's been a while since I was messing around with this, but I think I was specifically looking for the filter parameters which are present on `get()`, but not on `getAll()`. I was working with customer data, so I don't have it lying around anymore unfortunately.

I was looking for something along the lines of this:
```
    /**
     * @return Struct\GeneralInfo[]
     */
    public function getAll(string $field, $value): array
    {
        return $this->getItems(Struct\GeneralInfo::class, 'gen_info', $field, $value);
    }
```
https://github.com/plesk/api-php-lib/blob/f0c91a45f3ceb7073253e74ad2b07676de1de0fb/src/Api/Operator/Site.php#L88

Additionally the TypeError issue appears to be present in many other Operators as well:
https://github.com/plesk/api-php-lib/blob/f0c91a45f3ceb7073253e74ad2b07676de1de0fb/src/Api/Operator/Subdomain.php#L49
https://github.com/plesk/api-php-lib/blob/f0c91a45f3ceb7073253e74ad2b07676de1de0fb/src/Api/Operator/Webspace.php#L126
https://github.com/plesk/api-php-lib/blob/f0c91a45f3ceb7073253e74ad2b07676de1de0fb/src/Api/Operator/Customer.php#L41

I think I ended up hacking together my own implementation of the few endpoints I needed though, but thanks for looking into it.
