### ISSUE TITLE
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.

### ISSUE THREAD

**Issue by pindab0ter** [plesk/api-php-lib#125]
When requiring the package, the following warning appears:

```
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
```

**Comment by sibprogrammer** [comment]
@pindab0ter, the package has no such dependency. It seems you are using something else besides api-php-lib.
Try to reproduce by creating an empty directory and "requiring" the package.

**Comment by pindab0ter** [comment]
In that case, apologies for opening this.
