### ISSUE TITLE
PHP Version or error repository?

### ISSUE THREAD

**Issue by ZeroCrazy** [plesk/api-php-lib#129]
for which version of PHP is it allowed? I am using it in 8.2.9 and when I put the host (ip), username and password it does not generate any client...

```
require 'inc/core.php';
require 'vendor/autoload.php';

$client = new \PleskX\Api\Client("myip");
$client->setCredentials($s['plesk']['username'], $s['plesk']['password']);

$client->customer()->create([
    'cname' => 'Plesk',
    'pname' => 'John Smith',
    'login' => 'john',
    'passwd' => 'secret',
    'email' => 'john@smith.com',
]);
```

**Comment by sibprogrammer** [comment]
> for which version of PHP is it allowed? 

PHP 7.4, 8.0, and 8.2 are supported.

> it does not generate any client

The client raises the exception in the case of an API call problem. Ensure you don't suppress these exceptions.
