### ISSUE TITLE
Create Customer: howto set anything else than gen-info ?

### ISSUE THREAD

**Issue by michabbb** [plesk/api-php-lib#2]
when looking to the [code](https://github.com/plesk/api-php-lib/blob/master/src/PleskX/Api/Operator/Customer.php#L17)

the [api](http://download1.parallels.com/Plesk/Doc/en-US/online/plesk-api-rpc/index.htm?fileName=60289.htm) has much more than "gen-info", how shall that work with this code ???

**Comment by sibprogrammer** [comment]
Everything is ok here. customer > add operation has only "gen_info" as a child node.
There are some other cases. E.g. webspace > add has a problem that you mentioned.
One need to understand that the library is under development and in alpha stage.

You can always you the fallback ways for complicated scenarios.
See https://github.com/plesk/api-php-lib/blob/master/tests/ApiClientTest.php#L93
