### ISSUE TITLE
How to get all subscriptions of a particular user?

### ISSUE THREAD

**Issue by sburina** [plesk/api-php-lib#23]
Hello!

`$client->webspace()->get('owner-guid', 'xxxxx')`

returns only one result, althouth there could be more. Is there any way to get all user's subscriptions via API call?

I see Plesk returns the proper result with more records, but Operator _getItems method seems to take only the first one.

Thank you!

**Comment by sibprogrammer** [comment]
Webspace operator has getAll method for such purposes.
