### ISSUE TITLE
More webspace information

### ISSUE THREAD

**Issue by sburina** [plesk/api-php-lib#24]
Hello!

Is there a proper way to get more webspace information than defined in PleskX/Api/Struct/Webspace/GeneralInfo.php ? There are only two pieces of information in there currently.

**Comment by mrsombre** [comment]
Disk usage added by @baldhead 
Please, reopen and comment if more functionality needed or better send PR with new code.
Also, try a new [REST API](https://docs.plesk.com/en-US/onyx/api-rpc/about-rest-api.79359/)
