### ISSUE TITLE
Ever heard about CDATA ?

### ISSUE THREAD

**Issue by michabbb** [plesk/api-php-lib#3]
how is it possible to create a xml api and ignoring CDATA ???
thats like building a house without windows....  btw... http://disq.us/8ml8gk

**Comment by sibprogrammer** [comment]
Invalid report. This project is about the wrapper for XML-RPC API. Not about XML-RPC API itself. Reports that contains nothing expect generic complains will be closed immediately.

**Comment by michabbb** [comment]
f*** you is always a good answer, of course... 
but who is responsible to the api iteself and is a little bit more interested in the people who really use it ? what is the right place to get an ear ?

**Comment by sibprogrammer** [comment]
Here is the official place on how to get a support: http://sp.parallels.com/support/plesk-suite/plesk/
Btw I answered on the question about autoresponder and HTML content: http://download1.parallels.com/Plesk/Doc/en-US/online/plesk-api-rpc/index.htm?fileName=34492.htm

**Comment by michabbb** [comment]
thanks a lot
