### ISSUE TITLE
PHP warning in subdomain()->getAll() if there are no subdomains

### ISSUE THREAD

**Issue by vlikhtanskiy** [plesk/api-php-lib#32]
STEPS TO REPRODUCE:
On server without any subdomains run:
```
$client = new PleskX\Api\Client(...);
var_dump($client->subdomain()->getAll());
```

And check logs.

ACTUAL RESULT:
PHP Warning: Invalid argument supplied for foreach(); File: /usr/local/psa/admin/plib/modules/wp-toolkit/vendor/plesk/api-php-lib/src/PleskX/Api/Struct/Subdomain/Info.php, Line: 28

And output:
```
array(1) {
  [0]=>
  object(PleskX\Api\Struct\Subdomain\Info)#297 (4) {
    ["id"]=>
    int(0)
    ["parent"]=>
    string(0) ""
    ["name"]=>
    string(0) ""
    ["properties"]=>
    array(0) {
    }
  }
}
```

EXPECTED RESULT:
No PHP warning and empty array.

**Comment by sibprogrammer** [comment]
Fixed in scope of fbf97aee9fd8d27c33b745a26c8c75400b93ea32 commit.
