### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by RamonSmit** [plesk/api-php-lib#41]
Dear maintainer, 

Would you mind to please tag releases? We're dependent on `dev-master 0f080c6` at this moment, 
but I would appreciate to see release tags for new versions. So we don't have to pull directly from the repo like this. 

Thanks in advance,
Ramon

**Comment by xgin** [comment]
Hey, I agree with you.
We will also stick to releases in own packages.
The current version was marked with `v1.0.0` tag and available here: https://packagist.org/packages/plesk/api-php-lib#v1.0.0
