### ISSUE TITLE
Fatal Error when trying to create a customer

### ISSUE THREAD

**Issue by ghost** [plesk/api-php-lib#44]
When I use the following code:
```
<?php
error_reporting(-1);
ini_set('display_errors', 'On');
require("../../broomfieldhosting.co.uk/plesk-php-api/src/PleskX/Api/Client.php");
$client = new \PleskX\Api\Client('broomfieldhosting.co.uk');
$client->setCredentials('admin', '***************');

$client->customer()->create([
    'cname' => 'Plesk',
    'pname' => 'John Smith',
    'login' => 'john',
    'passwd' => 'secret',
    'email' => 'john@smith.com',
]);
?>
```
I get the error:
`
Fatal error: Uncaught Error: Class '\PleskX\Api\Operator\Customer' not found in /var/www/vhosts/broomfieldhosting.co.uk/broomfieldhosting.co.uk/plesk-php-api/src/PleskX/Api/Client.php:345 Stack trace: #0 /var/www/vhosts/broomfieldhosting.co.uk/broomfieldhosting.co.uk/plesk-php-api/src/PleskX/Api/Client.php(364): PleskX\Api\Client->_getOperator('Customer') #1 /var/www/vhosts/broomfieldhosting.co.uk/account.broomfieldhosting.co.uk/signup/stevejobs.php(8): PleskX\Api\Client->customer() #2 {main} thrown in /var/www/vhosts/broomfieldhosting.co.uk/broomfieldhosting.co.uk/plesk-php-api/src/PleskX/Api/Client.php on line 345`

**Comment by archiebaer** [comment]
I attemped to install via Composer by using this guide: https://support.plesk.com/hc/en-us/articles/115004023153-How-to-install-PHP-dependencies-using-Composer-in-Plesk-12-5-or-Plesk-Onyx-

**Comment by archiebaer** [comment]
So this is my first ever issue. I don't even use Plesk anymore.

**Comment by Gamer08YT** [comment]
I have the same Error but I can't install it via Composer I need another way...
