### ISSUE TITLE
Add Subscription to a User-Account.

### ISSUE THREAD

**Issue by bennetgallein** [plesk/api-php-lib#46]
Hey, I want to use this for automatic deployment of Webspaces if the User buys a Subscription in my Interface. I've looked trough the `tests/` directory and the source but didn't found anything regarding subscribing a user to a Service Plan. 
Maybe someone can help me?

**Comment by mrsombre** [comment]
Hello,
I suppose you need to add a subscription with Service plan. Look at \PleskXTest\WebspaceTest::testRequestCreateWebspace.
Reopen, if this suggestion is not useful.
