### ISSUE TITLE
Check if webspace exists

### ISSUE THREAD

**Issue by PierreSchwang** [plesk/api-php-lib#58]
Hello,
is there a better solution than using try-catch to see if a webspace exists? Currently I do it this way:

```php
try {
    $client->webspace()->get('name', 'something')
    // Webspace exists
} catch (PleskX\Api\Exception $e) {
    // Webspace does not exists
}
```

But the problem is that every exception is catched (be it due to server errors or wrong parameters / filters).

**Comment by seem2810** [comment]
Hello,
have you tried to save the response to a variable? 
e.G.
`$webspace = $client->webspace()->get('name', 'something');`
Then you can check if it isn't false:
`if($webspace !== false) return "Webspace exists";`
