### ISSUE TITLE
 Need help using the api php lib plesk

### ISSUE THREAD

**Issue by ValentinRgt** [plesk/api-php-lib#60]
FR

Bonjour,

Actuellement, j'essaie de comprendre comment la Plesk API PHP LIB fonctionne... Malheureusement sur le github il y a 3 lignes d'explications et après démerder vous.... Quelqu'un serait en mesure de m'aider pour gérer cette librairie php plesk sur mon site svp ?

Cordialement,

----

EN

Hello, 

Currently, I'm trying to understand how the PHP Plesk PHP LIB works ... Unfortunately on the github there are 3 lines of explanations and after demerder you .... Someone would be able to help me to manage this php plesk library on my site please? 

Regards,

**Comment by espitsyna** [comment]
Hello, 
For additional examples see tests/ directory.
