### ISSUE TITLE
How to set IPv4 and IPv6 when creating a webspace?

### ISSUE THREAD

**Issue by Sarsum** [plesk/api-php-lib#63]
Hi,

is it possible to set multiple ip-adresses (one ipv4 and one ipv6) when creating a webspace?

If so, how? - Otherwhise: Could this be added?

Thanks and regards!

**Comment by Sarsum** [comment]
So, I tested myself a little bit and found this solution:
`if (isset($properties['ip_address'])) {
	if (is_array($properties['ip_address'])) {
		foreach ($properties['ip_address'] as $value) {
			$infoHosting->addChild("ip_address", $value);
		}
	} else {
		$infoHosting->addChild("ip_address", $properties['ip_address']);
	}
}`
I just replaced it with the existing code in https://github.com/plesk/api-php-lib/blob/c358e6aaf65e3bbc926fbb1e61ec242dee9e1e5c/src/Api/Operator/Webspace.php#L70-L72 and it worked.

Could someone please change that in the code for me?
I don't know how to test it out of Phpstorm (especially the test for it)...

**Comment by sibprogrammer** [comment]
The suggested change has been applied. Thank you!
