### ISSUE TITLE
What exectly is happenning here?

### ISSUE THREAD

**Issue by savaticus** [plesk/api-php-lib#64]
https://github.com/plesk/api-php-lib/blob/c358e6aaf65e3bbc926fbb1e61ec242dee9e1e5c/src/Api/Operator/Database.php#L38

Viewing the API spec, I cannot fathom why this code exists. What if there is an ampersand in the password? Please help me understand the point here...

**Comment by savaticus** [comment]
I would really appreciate some kind of a response.

**Comment by sibprogrammer** [comment]
This is exactly the case. The value can contain & that will be unescaped entity during transformation to XML. So construction addChild is not safe for such cases. To be honest I would like to keep only the line "$info->$name = $value;" for simplicity (and eliminate "if" construction and addChild block).  Probably we'll do it sooner or later. 

P.S. There are several other places where addChild construction can lead to problems with value escaping. We'll need to fix them as well.
