### ISSUE TITLE
How to get status of webspace (active,suspended,disabled)

### ISSUE THREAD

**Issue by fferraro87** [plesk/api-php-lib#67]
Hi,

can i get status of webspace such as active,suspended or disabled?

Thanks for your work!

**Comment by aadlung** [comment]
PleskX\Api\Struct\Webspace\Info does not include the "status" variable - like the others it seems (I added it to my ServicePlans for example).

If there is no possibility of a pull request or change - you can add it manually to the file Info.php in the Struct\Webspace folder. Although this will be lost with every composer or package update

```
namespace PleskX\Api\Struct\Webspace;
class Info extends \PleskX\Api\Struct
{
    /** @var integer */
    public $id;
    /** @var string */
    public $guid;
    /** @var string */
    public $status;
    public function __construct($apiResponse)
    {
        $this->_initScalarProperties($apiResponse, [
            'id',
            'guid',
            'status'
        ]);
    }
}
```

**Comment by fferraro87** [comment]
Thanks a lot, now i can get it, thanks again
