### ISSUE TITLE
No user creation without pre-activation available?

### ISSUE THREAD

**Issue by 1d0navan** [plesk/api-php-lib#70]
Hello,

your example works great: 
$client->customer()->create([
			'cname' => 'Plesk',
			'pname' => 'John Smith',
			'login' => 'john',
			'passwd' => 'secret',
			'email' => 'john@smith.com',
		]);

is there a parameter, which can deactivate the user, so he needs to activate the account by himself?

**Comment by 1d0navan** [comment]
btw. yo guys really need to start commenting your tests :D

**Comment by simonsolutions** [comment]
As far as I understood Plesk and the Plesk API interface there is only a possibility to set a given password, not to send a user e.g. a link to activate the account by setting a password.

**Comment by sibprogrammer** [comment]
> so he needs to activate the account by himself?
Plesk doesn't have such a workflow, but you can use the workaround described above or implement your own activation process on top of it.
