### ISSUE TITLE
[Suggestion] - README.md needs documentation

### ISSUE THREAD

**Issue by ghermans** [plesk/api-php-lib#8]
At this point It isn't at all obvious for everyone how to start using this package.
For that i would like to suggest to add a minimum set of examples demonstrating how to use this package.

**Comment by sibprogrammer** [comment]
It's a good point.

**Comment by ghermans** [comment]
@sibprogrammer i am working on this right now

**Comment by sibprogrammer** [comment]
Solved in scope of 72836f7f4fbff39cec8adf276a101326e0eeabe6
