### ISSUE TITLE
Retrieve site-id with the site guid

### ISSUE THREAD

**Issue by BlueRayNL** [plesk/api-php-lib#88]
Hi,

not really an issue more a question,
how can i retrieve the site-id (forexample 20) based on the guid (forexample f0bf242345-50ed-4d86-81a3-61f06b12adfd3d0)?

many thanks !

**Comment by rene-gates** [comment]
Hi, 

I would use "$client->site()->getAll()" to retrieve an array with all sites. After that loop all items and look for a matching guid. When you find one, you got your site-id.

**Comment by simonsolutions** [comment]
I proposed change #108 then you get an indexed array of all sites, looping through and getting the id is an easy way to find the site-id based on a given site-guid.

**Comment by sibprogrammer** [comment]
It was addressed in scope of a665af5ebf853f6fedf83b010c7c32d5744d94ee
See https://github.com/plesk/api-php-lib/commit/a665af5ebf853f6fedf83b010c7c32d5744d94ee#diff-ef1e45a8ba0a90537d36ecced8a61efd0ba65ef9b162f0b47f960a7266ef7d87R67-R70 for details
